### ISSUE TITLE
Declarative API for useGet

### ISSUE THREAD

**Issue by stereobooster** [contiamo/restful-react#151]
### Declarative API

Current API has non-declarative parts, for example, `cancel`, `refetch`, `lazy`.

Purely declarative API would not have this, instead it would do this

- to `cancel` unmount component with hook
- to `refetch` bump `key` of component with hook
- `lazy` not needed, but we can add `skip`, to prevent immediate fetching (setting `skip` to true will cancel current request)

### Refetch vs cache

How refetch will behave in [presence of cache](https://github.com/contiamo/restful-react/issues/150)?

Without refetch we can send request of each cache miss e.g. if component remounts and there is no fresh data in the cache it will submit request again. Not typical API though 🤔 

Not sure where I'm going with this. WDYT?

**Comment by TejasQ** [comment]
- I think `cancel` is still quite declarative. For example, "cancel running query" in a long running sequel query. There really isn't room to unmount anything here to cancel requests. We want an explicit click on a button to do this.

- Similarly, I think `refetch` is more declarative than imperatively bumping a key. Namely, `refetch()` communicates (declares?) _what_ to do instead of ambiguously bumping a key to rerender.

- I think renaming `lazy` to `skipInitialRequest` could work, but we'd need a strong case to justify breaking the API.

- I suggest discussing cache refetch in the specific issue about the cache.
