### ISSUE TITLE
[Question] Hook state dependency

### ISSUE THREAD

**Issue by vitorverasm** [contiamo/restful-react#192]
Hi everyone 👋 . I wanted to know how can I specify to my custom API generated hooks in which state change they should run?

Like we do when we make async calls on useEffect.
```jsx
  useEffect(() => {
    fetchData();
  }, [page]); // Only call fetchData on page change.
```

**Comment by DavidSun0403** [comment]
You can define your own local state. The code should like:
if (!loading && !data) {
    setData(data);
  }
I tried and succeeded.

**Comment by fabien0102** [comment]
@vitorverasm You can totally fetch data on demand, even if it's not really make sense for pagination. Since the page is part of the request (usually in queryParams), the request will re-run everytime you update the `page`

An example to illustrate:
```tsx
const [page, setPage] = useState(1);
const {data} = useMyGeneratedGet({queryParams: {page}})

// This will refetch on every page change
```

If you want more control:
```tsx
const [page, setPage] = useState(1);
const {data, refetch} = useMyGeneratedGet({lazy: true, queryParams: {page}})

useEffect(() => refetch(), [page]);
// do the same, the `lazy: true` avoid to fetch automatically
```

You can also store the `data` in a state, if you want to consolidate multiple pages for example 😉 

Let me know if I answer your question 😃 (if not, we will figure with more examples ^^)

PS: Sorry for the late response, it's was a bit the rush 😅

**Comment by vitorverasm** [comment]
Thank you for the response. I figured out the page on the query parameters when I was solving my task. Calling refetch on the useEffect and binding to page is a good tip. Thanks for the explanation.
