### ISSUE TITLE
Support stricter typing on `resolve` function

### ISSUE THREAD

**Issue by seanlaff** [contiamo/restful-react#214]
https://github.com/contiamo/restful-react/blob/9456b8198045cb6551711bb248973400ad88caf6/src/useGet.tsx#L35

Can we switch this from `any` to `TData` or was this an intentional design decision to act as an escape hatch?

**Comment by fabien0102** [comment]
This is totally intentional (I have `any` 😁).
This is because we asume that everything coming from the backend is not typesafe and need to be sanitazed somehow. 

Usually we use https://github.com/gcanti/io-ts to validate and give proper types, but yes, everything from outside (backend response, localstorage, url params…) are `any` by nature and need to be checked at runtime to be typesafe 😉

**Comment by fabien0102** [comment]
If you want to trust this, you can just specify the type of the function since `any` is compatible with `TData`, so:

```tsx
const { data } = useGet("/", { resolve: (data: MyResponse) => data });
```

But keep in mind that in real life, this can really `any` and you can have surprises 😉

**Comment by seanlaff** [comment]
Ah I think I better understand your intent with the `any` typing.

As a client I may way to write something like 
`const { data } = useGet<MyType>("/", { resolve: (data) => data });`

In which case my resolve function is responsible for parsing the data into the generic type I've provided. I was coming at this from the case of the codegen use case where I can trust TData a tad more, but I think as general behavior the `any` makes sense.

Thanks for the insight
