### ISSUE TITLE
React Native - Call api hooks in middleware (Reducers)

### ISSUE THREAD

**Issue by Sarran2003** [contiamo/restful-react#224]
**Describe the bug**
Hi, Is there a best practice or way to use hooks in middleware like reducers in react native. If i do any api call using hooks in reducers, getting below error.

Error: invalid hook call. Hooks can be called inside of the body of function component.

**Expected behavior**
api calls should be success without any issues.

**Additional context**
If this is the expected behavior which hooks cannot use in middleware. do we need to go for non hooks api call like fetch or axios?

Thanks in advance.

**Comment by hydrosquall** [comment]
I think you'd be looking for a similar API as what we described in https://github.com/contiamo/restful-react/issues/223 , since hooks cannot be used outside of React components. 

The current approach I'm using is using the autogenerated types from `restful-react` and using them to type the arguments and responses for your fetch or axios based data fetchers.

**Comment by fabien0102** [comment]
You can even going a bit deeper that maintaining your fetch/axios manually with the new `customGenerator`

https://github.com/contiamo/restful-react/blob/f8b25ec056fe6b9bee919fbc62453c57d8464d31/examples/restful-react.config.js#L20-L40

We are using this to generate some `fetch` component internally when hooks are not practicles, please give a try and let me know if it fit your usecase 😀 (I would love to see your reducers generator!)
