### ISSUE TITLE
[Feature Request] Generate Request Body Type for Mutate Operations (like POST)

### ISSUE THREAD

**Issue by hydrosquall** [contiamo/restful-react#225]
**Is your feature request related to a problem? Please describe.**

- The request body type is inlined, instead of getting a custom type (like the `MyOperationNameRequestBody`, based on the behavior for GET based resources

**Describe the solution you'd like**

When user documents a POST request in their OpenAPI spec, a type called `OperationNameRequestBody` gets generated. Currently, the type is inlined directly into the generic for the `useMutate` call. 

**Describe alternatives you've considered**

- We can manually modify the generated file by DRYING out the `OperationNameRequestBody` line during prototyping, but we'd want to come up with some automation before taking that this library to production.

**Additional context**

- We migrated an endpoint from making GET to making POST requests. We moved the query parameters from GET to POST, and found that the `useMutate` generated code didn't have a generated type for the `RequestBody`.

**Comment by fabien0102** [comment]
Hi @hydrosquall,

Thanks for your feedback, as an alternative I can suggest you to upgrade your openAPI to use schemas, this is how we use it internally (and also why we don't run in this issue)

Example:
```yaml
requestBody:
  required: true
  description: SQL query to profile
     content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProfileRequest"
```

So I have a `ProfileRequest` type generated like this:

```tsx
export interface ProfileRequest {
  projectId: string;
  sql: string;
  sampleSize?: number;
}
```

Even better, you can also extract your request bodies to `#/components/requestBodies/` and you will have a nice `RequestBody` suffix (note to myself: we should use this in my company 😁)
 
https://github.com/contiamo/restful-react/blob/1f9452bd166526369b9c9226979e016f02284dd3/src/scripts/import-open-api.ts#L91

Otherwise it should not be too hard to implement, just some directions if you want to tacle this

The type are generated here:
https://github.com/contiamo/restful-react/blob/1f9452bd166526369b9c9226979e016f02284dd3/src/scripts/import-open-api.ts#L295

And injected a bit below 😁 I also invite you to add/update the existing unit tests to support you in this change (if you are interrested of contributing of course)

For the record, my concern was to avoid name conflicts between types in `#/components/` and the generated one "on the fly", after it's a bit unlikely to have both in the same specs, since it often part of convention rules, so I guess it can be fine.

**Comment by fabien0102** [comment]
I had a bit of motivation this morning, I have the feature locally 😉 I just need to configure my new computer to be able to commit 😁 Should happens this weekend! I keep you up to date.

**Comment by hydrosquall** [comment]
I've tried this out, and it works very well!
