### ISSUE TITLE
[Question] useMutate and useGet API design - Unifying the Return Types

### ISSUE THREAD

**Issue by hydrosquall** [contiamo/restful-react#227]
## Motivation

I was initially confused by how `useGet` and `useMutate` have different return types, in that when I switched an endpoint from one to the other, I thought that they'd both return `refetch` and `data`.

In the case of this endpoint, the semantic meaning of what that endpoint did hadn't changed, it was a change made due to technical limitations around url length for a GET request which didn't apply to POST body size.

## Ask

My question: has there been previous discussion / interest in unifying the API return types for both types of hook (useGet and useMutate)? I've used the `useGet` approach more, but haven't thought about it long enough to know which I'd prefer if the two did end up converging. 

## Appendix

Below is a sketch of an (untested) wrapper one might write to convert a `useMutate` hook to have the same return signature as `useGet`, with an additional parameter for the request body.

```jsx
const usePostDog = (body, requestOptions) => {
  const { mutate, loading } = useMutate({
    verb: "POST",
    path: `/petstore/dog`
  });

  const [data, setData] = setState(null);

  const refetch = useCallback((body, requestOptions) => {
    mutate(body, requestOptions).then(response => {
      setData(responseData);
    });
  }, []);

  return {
    refetch,
    loading,
    data
  }
};

// Usage example
const body = {
  tags: ['good', 'hungry']
  name: 'rex'
};
const requestOptions = {};

const { data, refetch } = usePostDog();
```
```

**Comment by fabien0102** [comment]
Hello @hydrosquall,
The main idea is to add a bit of semantic around the usage of get and mutate.
With get, I just want my data (that I can `refetch` and that I consume usually directly with `data`), and with mutate I usually just want to send something to backend (so call `mutate` and do something on `.then()`)

To be totally transparent, this API is heavily inspired by apollo 😉 You have this two main concept in graphql and we like this semantic (I know that I can't destroy anything by calling `useGet` and I'm a bit more careful when I call `useMutate` 😁)

Of course, since you can customize the fetch options in each hook, nothing fight you against using `useMutate` with a `GET` verb or `useGet` with `POST`. This is just an attempt to put conventions and semantic in the REST world (that is not a specification, so you can do what ever you want with ^^)

I hope this answered your question, it never easy to design an API that is obvious for everybody, probably the harder part of ours jobs 😅

**Comment by hydrosquall** [comment]
Understood, thanks @fabien0102 for the thorough explanation! I didn't realize that the following was possible:

> nothing fight you against using useMutate with a GET verb or useGet with POST.

**Comment by fabien0102** [comment]
I guess we can close this question, ping me if you have others questions 😃

**Comment by ricardona** [comment]
@fabien0102 

> useGet with POST.

Could you give me an example of how to do this?

We have some legacy APIs using POST to return data.
