### ISSUE TITLE
How to assign type when using code generator

### ISSUE THREAD

**Issue by webwmagnet** [contiamo/restful-react#251]
Good afternoon! Thanks again for this miracle.

**Problems**
Please tell me how to assign a return type when resolve, I generate with - restful-react Swagger v2 specification. It’s hard for me to write the idea correctly, but I think the screenshot will be clearer. The bottom line is that I do not want to set the value {data: any}, but I want to assign the type that I take. 

**Screenshots**
_**use**_
![Problems](https://i.ibb.co/1vf5DBr/2020-03-23-14-00-41.png)

_**model**_
![Problems](https://i.ibb.co/P1JrwLF/2020-03-23-14-06-09.png)
_**type response**_
![Problems](https://i.ibb.co/7vcTsN2/2020-03-23-14-06-16.png)
_**type category **_
![Problems](https://i.ibb.co/fD7bJ5k/2020-03-23-14-06-21.png)

**Comment by fabien0102** [comment]
I think I understand your problem ^^

```ts
/**
   * A function to resolve data return from the backend, most typically
   * used when the backend response needs to be adapted in some way.
   */
  resolve?: (data: any) => TData;
```

`resolve` always receive `any` by design, because it come from the backend, and we can't trust this as is. 

The idea was to use something like [io-ts](https://github.com/gcanti/io-ts) to decode/validate the data from the backend. BTW, the `resolve` is totally optionnal, more for advanced cases, but this is the idea behind it 😉 

(and yes, I know, it's annoying to have `any` there, but as a library author I'm also trying to educate people about what is safe or not 😁 And yes, I had a lot bad experience where the backend was not following the specs (because we are all humans and errors is part of our life) and where my app was crashing because too much trust 😞)

I still want to add a "io-ts" generator at some point, but this is a huge task, the idea will be to validate the backend response with the open-api specs on the runtime, this will increase the typesafety of all ours products!

**Comment by webwmagnet** [comment]
I understood, on the whole, yes, it’s logical to trust these backs, to insert sticks in wheels (a joke).
Thank you, I will then be without resolve)
