### ISSUE TITLE
Improve API for nested <Get>s

### ISSUE THREAD

**Issue by micha-f** [contiamo/restful-react#3]
**Is your feature request related to a problem? Please describe.**
I think that it is 

- not obvious from looking at code that `path="string"` will be appended to the path(s) of parent `<Get>`(s)
- not safe to assume that components will only make requests that fit with the nesting of paths 

**Describe the solution you'd like**
I propose to update the API so that
```
<Get path="/persian"> // makes a request to /persian
<Get path={(parentPaths: string[]) => `${parentPath.join("/")}/persian`} > // makes a request to /cats/persian
```
where `parentPaths` is an array of the normalized `path`s (stripped of trailing `/`) of the parent `<Get>`s.

**Describe alternatives you've considered**

1. `parentPaths` could also be a string of the concatenated parent paths. I believe however that the use of an array is more flexible if we go with nested `<Get>`s affecting each other.
1. Alternatively or additionally we could introduce a `<Path>` component that affects the nesting while `<Get>`s don't affect each other's path at all. This would allow us to do things like this, too:

```
<Path path="/author/123">
  <Get path={ (path: string) => `${path}/bio`>
  <Get path={ (path: string) => `${path}/books`>
</Path>
```

**Comment by TejasQ** [comment]
Typically, components that nest also map to nested resources, hence the current design. I could also make the docs a little bit clearer about that API.

I think if we decide to implement your feature request, it'll have to be an _add_ instead of a _modify_, which will be backwards compatible. So specced out, `path` could be a string, in which case it nests, _or_ a function in which case it works the way you require. I'm still fairly unclear about the use case/need it'll be meeting.

From your second considered alternative, the `<Path />` component, the only way its children would have access to the `path` from the `Path` component in that case is via function children. Your sample would actually look like

```jsx
<Path path="/author/123">
{(path) => <>
  <Get path={`${path}/bio`}>
    {(data => <div>{data}</div>}
  </Get>
  <Get path={`${path}/books`}>
    {(data => <div>{data}</div>}
  </Get>
</>}
</Path>
```

I'm not sure that is easy to read. Seems to me like your preferred solution would be the way to go on this.

I'm curious: is there a particular use case you have in mind that the current API is not meeting?

**Comment by micha-f** [comment]
Closing this after discussion with @TejasQ. You can always specify a different base in a Get and be completely independent from nesting.
