### ISSUE TITLE
"refetch" cause react components to re-render always

### ISSUE THREAD

**Issue by Aashu-stockgro** [contiamo/restful-react#349]
**Describe the bug**
When we use refetch in a component it is always causing a re-render of the component. we have a use case where we want to do a api call every 5 seconds and only re-render the component if current data !== previous data

**To Reproduce**

const { data, loading, refetch } = useGet({ path: "Any Path"  })
useEffect(() => {
    let timer1 = setInterval(() => refetch(), 5000)
    return () => clearInterval(timer1)
  }, [])

Puth the above in you react component and you will notice that the component re-renders every 5 seconds

**Expected behavior**

On refetch before re-rendering the component I would like to do a deep comparison(between current and previous response) using lodash for example and then re-render

**Comment by fabien0102** [comment]
Since `loading` will go to `true` and `false`, this is totally expected. For polling behaviour we are usually using some custom fetcher instead of restful-react, so you can have any custom behaviour.

Another solution is to memoized the component that received `data`, the parent will still re-render but this should not affect the perf at all.

**Comment by Aashu-stockgro** [comment]
@fabien0102 thanks for the quick response and the solution you mentioned.

Memoization of  the child component works.. Its just that have to create a child component for this specific purpose...

I am closing the issue for now. Please see if some solution can be implemented in the future. I do understand that managing loading state and data simultaneously is tricky..
