### ISSUE TITLE
Consider renaming `host` to `base`

### ISSUE THREAD

**Issue by micha-f** [contiamo/restful-react#4]
As this property might also contain a base path I would like to propose renaming it:

```
<RestfulProvider base="https://dog.ceo/api"> ...
```

**Comment by TejasQ** [comment]
Great idea. Since this change will break the API, let's slate it for the next major version. I also think adding both props side-by-side in a new minor release will make it easier to adopt and provide a solid migration path going forward.

Thanks! You can expect this snippet to work in the next minor release!

**Comment by TejasQ** [comment]
Fixed in #7
