### ISSUE TITLE
Install from npm the built file is not compiled to es5.

### ISSUE THREAD

**Issue by chilijung** [contiamo/restful-react#52]
**Describe the bug**
Just install the npm pkg, the files inside `lib` folder is not compatible into es5... I can see `import` etc syntax in lib folder.

```
node_modules/restful-react/lib/index.js:1
  (function (exports, require, module, __filename, __dirname) { import Get from "./Get";
                                                                       ^^^

  SyntaxError: Unexpected identifier
      at new Script (vm.js:74:7)
      at createScript (vm.js:246:10)
      at Object.runInThisContext (vm.js:298:10)
      at Module._compile (internal/modules/cjs/loader.js:657:28)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
      at Module.load (internal/modules/cjs/loader.js:599:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
      at Function.Module._load (internal/modules/cjs/loader.js:530:3)
      at Module.require (internal/modules/cjs/loader.js:637:17)
```

**To Reproduce**
just install from npm.

**Expected behavior**
Should work in browsers

**Comment by TejasQ** [comment]
Hi chilijung! Thanks for the report! The issue here is because restful-react is a _library_ and is generally expected to run inside a module bundler: webpack, parcel, etc. since it exposes _React components_, which typically also are run in a bundler in order to allow the JSX to be transpiled to regular JavaScript.

Because of this, you require a bundler and the expected behavior of "Should work in browsers" is valid _only when it is bundled_.

I'm curious – does your project use React?

**Comment by chilijung** [comment]
Yes, but we are using NextJS, NextJS default external `node_modules` compile through webpack bundler. Without overwrite its internal settings, it is unusable.

**Comment by chilijung** [comment]
Btw, I really love the concept. We are using this library with `apolloClient`. Since we incremental changing our APIs, this allows us to completely drop redux to resolve Restful APIs in local state.

**Comment by TejasQ** [comment]
So providing a UMD build would solve the problem. Excellent. We'll get on this. Would you like to submit a PR, or shall we?

**Comment by chilijung** [comment]
I've thought about that but I don't know how `operational-scripts` works 😅

https://github.com/contiamo/restful-react/blob/master/package.json#L38

**Comment by TejasQ** [comment]
It just does this:

https://github.com/contiamo/operational-scripts/blob/9f45ef358ed37ad8b7ced7640909284d13e285e5/index.js#L60-L66

It runs the TypeScript compiler and that's it. 

I guess we can:

a) Upgrade `operational-scripts` to have the `build` script accept flags and pass `--target es5` to it,
b) Use rollup, maybe even making the build script of `operational-scripts` use rollup to package for npm instead of just raw `tsc`.
c) Export a UMD global with `tsc` but I'm not sure how to do this.

I'd like to get some thoughts here: yours, @chilijung, but also some of the team: @peterszerzo and @fabien0102.

Let's decide on a direction and go.

I personally think using rollup in `operational-scripts` as the safest bet but I'd love some team input.

**Comment by fabien0102** [comment]
Totally agree to introduce rollup and `--target es5` or `build --for umd`. We already have an open issue for this https://github.com/contiamo/operational-scripts/issues/20 😉

**Comment by TejasQ** [comment]
@chilijung want to try to implement that? ^

**Comment by chilijung** [comment]
I found a workaround of this issue in nextjs, I'm in a tight deadline for our project. I don't have time to dig in further codebases. However, I'll create PRs for features and fixes of `restful-react` if needed for my use case, thanks.

**Comment by davidgoli** [comment]
This also does not work with Jest and create-react-app out of the box.

It works fine when importing into app code via create-react-app, but the default jest config in create-react-app does not pass `node_modules` to Babel, so it's not able to run Jest tests. I can open a new issue if desired, but it seems related here.

**Comment by davidgoli** [comment]
For the record, I was able to implement a workaround as mentioned here:

https://github.com/facebook/create-react-app/issues/2537#issuecomment-390341713

**Comment by TejasQ** [comment]
We use rollup now, which should solve this issue. If it's still an issue, please let me know and we'll reopen.
